### ISSUE TITLE
Char type error

### ISSUE THREAD

**Issue by dragazhar** [CoCoViLa/CoCoViLa#110]
If we create field char operchar; with type char and:
1. use + as input we will get error EquationException Error in equation 'Math_0.operchar = +'. Misplaced operator.
2. use '+' as input we will get Syntax error on line 'Math_0.operchar = '+''
3. use "+" as input we will get 1. ERROR in Geometry (at line 11)  Math_0.operchar = "+";
Type mismatch: cannot convert from String to char
4. use number 1 as input we will get Math_1.operchar = 

**Comment by MastaP** [comment]
> 4. use number 1 as input we will get Math_1.operchar =
That's because 1 is an invisible symbol in ASCII

only case 2 is valid and should be fixed

**Comment by dragazhar** [comment]
I think that char must be valid without any '', so 1 is 1, not some invisible symbol in ascii, for example string is valid without ""
