### ISSUE TITLE
parsing problem and partial program generated

### ISSUE THREAD

**Issue by vkotkas** [CoCoViLa/CoCoViLa#111]
From http://www.ioc.ee/~vahur/DynamicSystemSimulator_problem.zip
Can be found an example where in the Integrator specification initstate is specified twice but the compiler does not complain.

When a program is composed from the scheme problem.syn the resulting code unfolds and folds the aliases correctly, but does not call the methods in the subtasks.

**Comment by MastaP** [comment]
> When a program is composed from the scheme problem.syn the resulting code unfolds and folds the aliases correctly, but does not call the methods in the subtasks.

@vkotkas That's because you're setting the ```initstate``` incorrectly. 
It is set when initstate is passed on the first call of the subtask ```[state -> nextstate, allDrawn]```, no need to call ```[initstate -> state], initstate -> integInit {initIntegral};``` at all.
The same way there's no need for ```initstate, initstate.length -> state {init};``` in the Integrator.
https://dl.dropboxusercontent.com/u/99448284/DynamicSystemSimulator_fixed.zip
